name: os_version

on:
  workflow_dispatch:
  
jobs:
  unbuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo lsb_release
  macos:
    runs-on: macos-latest
    steps:
      - run: echo sw_vers -productVersion
  windows:
    runs-on: windows-latest
    steps:
      - run: echo Get-ComputerInfo
      
